name: Publish package to the Maven Central Repository

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get release version
        id: get_version
        run: |
          echo "RELEASE_VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')" >> $GITHUB_ENV

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>ossrh</id>
                <username>${{ secrets.OSSRH_USERNAME }}</username>
                <password>${{ secrets.OSSRH_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_KEY_SECRET }}" | gpg --import

      - name: Publish package
        run: mvn --batch-mode deploy -P release -Drelease-version=${{ env.RELEASE_VERSION }} -DskipTests
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}

      - name: Clean up Maven settings
        run: rm -rf ~/.m2/settings.xml
